version: '2.1'

networks:
  test:
    name: fabric_test

services:
  explorerdb.universidades.com:
    image: postgres:13.2
    container_name: explorerdb.universidades.com
    hostname: explorerdb.universidades.com
    environment:
      - POSTGRES_DB=fabricexplorer
      - POSTGRES_USER=hppoc
      - POSTGRES_PASSWORD=password
    volumes:
      - ./explorer-db:/var/lib/postgresql/data
    networks:
      - test

  explorer.universidades.com:
    image: hyperledger/explorer:1.1.8
    container_name: explorer.universidades.com
    hostname: explorer.universidades.com
    environment:
      - DATABASE_HOST=explorerdb.universidades.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ../organizations:/opt/explorer/organizations
      - ./explorer-config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer-connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./explorer-wallet:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      - explorerdb.universidades.com
    networks:
      - test 